"""
HTML Exporter for Formatted Documents.

Exports FormattedDocument to styled HTML format with embedded CSS
for beautiful rendering of Gurbani quotes and sections.
"""
import logging
from pathlib import Path
from typing import List

from core.models import FormattedDocument, DocumentSection, QuoteContent
from exports.base_exporter import BaseExporter

logger = logging.getLogger(__name__)


class HTMLExporter(BaseExporter):
    """
    Exports formatted documents to HTML format.
    
    Produces styled HTML with:
    - Embedded CSS for Gurbani formatting
    - Responsive design
    - Print-friendly styles
    """
    
    def __init__(self):
        """Initialize HTML exporter."""
        super().__init__("html", ".html")
    
    def _export_impl(
        self,
        document: FormattedDocument,
        output_path: Path
    ) -> Path:
        """
        Export document to HTML file.
        
        Args:
            document: FormattedDocument to export
            output_path: Path where HTML file should be saved
        
        Returns:
            Path to exported HTML file
        """
        html_content = self._generate_html(document)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.debug(f"Exported HTML document: {output_path} ({len(html_content)} characters)")
        
        return output_path
    
    def _generate_html(self, document: FormattedDocument) -> str:
        """
        Generate complete HTML document.
        
        Args:
            document: FormattedDocument to convert
        
        Returns:
            Complete HTML string
        """
        lines: List[str] = []
        
        # HTML header
        lines.append("<!DOCTYPE html>")
        lines.append('<html lang="en">')
        lines.append("<head>")
        lines.append("    <meta charset='UTF-8'>")
        lines.append("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
        lines.append(f"    <title>{self._escape_html(document.title)}</title>")
        lines.append("    <style>")
        lines.append(self._get_css())
        lines.append("    </style>")
        lines.append("</head>")
        lines.append("<body>")
        
        # Document header
        lines.append("    <div class='document-header'>")
        lines.append(f"        <h1>{self._escape_html(document.title)}</h1>")
        lines.append("        <div class='metadata'>")
        lines.append(f"            <p><strong>Source:</strong> {self._escape_html(document.source_file)}</p>")
        lines.append(f"            <p><strong>Created:</strong> {document.created_at}</p>")
        if document.metadata:
            total = document.metadata.get('total_segments', len(document.sections))
            lines.append(f"            <p><strong>Total Sections:</strong> {total}</p>")
        lines.append("        </div>")
        lines.append("    </div>")
        
        # Sections
        lines.append("    <div class='document-content'>")
        for section in document.sections:
            section_html = self._format_section_html(section)
            lines.append(section_html)
        lines.append("    </div>")
        
        # Footer
        lines.append("    <div class='document-footer'>")
        lines.append("        <p class='footer-note'>Generated by Shabad Guru</p>")
        lines.append("    </div>")
        
        lines.append("</body>")
        lines.append("</html>")
        
        return "\n".join(lines)
    
    def _format_section_html(self, section: DocumentSection) -> str:
        """
        Format a document section as HTML.
        
        Args:
            section: DocumentSection to format
        
        Returns:
            HTML string
        """
        lines: List[str] = []
        
        # Section container
        section_class = f"section section-{section.section_type}"
        lines.append(f"        <div class='{section_class}'>")
        
        # Section header
        header = self._get_section_header(section.section_type)
        if header:
            lines.append(f"            <h2 class='section-header'>{header}</h2>")
        
        # Content
        if isinstance(section.content, QuoteContent):
            lines.append(self._format_quote_html(section.content))
        else:
            # Regular text content
            text = str(section.content)
            # Preserve line breaks
            text_html = self._escape_html(text).replace('\n', '<br>')
            lines.append(f"            <div class='section-text'>{text_html}</div>")
        
        # Timestamp
        if section.start_time is not None:
            time_str = self._format_timestamp(section.start_time)
            lines.append(f"            <div class='timestamp'>Time: {time_str}</div>")
        
        lines.append("        </div>")
        
        return "\n".join(lines)
    
    def _format_quote_html(self, quote: QuoteContent) -> str:
        """
        Format a Gurbani quote as HTML.
        
        Args:
            quote: QuoteContent to format
        
        Returns:
            HTML string
        """
        lines: List[str] = []
        
        lines.append("            <div class='quote-block'>")
        
        # Gurmukhi text (primary, large, centered)
        lines.append(f"                <div class='quote-gurmukhi'>{quote.gurmukhi}</div>")
        
        # Roman transliteration
        if quote.roman:
            lines.append(f"                <div class='quote-roman'>{self._escape_html(quote.roman)}</div>")
        
        # English translation
        if quote.english_translation:
            lines.append(f"                <div class='quote-english'>{self._escape_html(quote.english_translation)}</div>")
        
        # Metadata
        metadata_parts = []
        if quote.source:
            metadata_parts.append(f"<strong>Source:</strong> {self._escape_html(quote.source)}")
        if quote.ang:
            metadata_parts.append(f"<strong>Ang:</strong> {quote.ang}")
        if quote.raag:
            metadata_parts.append(f"<strong>Raag:</strong> {self._escape_html(quote.raag)}")
        if quote.author:
            metadata_parts.append(f"<strong>Author:</strong> {self._escape_html(quote.author)}")
        
        if metadata_parts:
            lines.append(f"                <div class='quote-metadata'>{', '.join(metadata_parts)}</div>")
        
        # Context lines
        if quote.context_lines:
            lines.append("                <div class='quote-context'>")
            lines.append("                    <strong>Context:</strong>")
            lines.append("                    <ul>")
            for context_line in quote.context_lines:
                lines.append(f"                        <li>{self._escape_html(context_line)}</li>")
            lines.append("                    </ul>")
            lines.append("                </div>")
        
        lines.append("            </div>")
        
        return "\n".join(lines)
    
    def _get_section_header(self, section_type: str) -> str:
        """Get HTML header for section type."""
        headers = {
            "opening_gurbani": "Opening Gurbani",
            "fateh": "Fateh",
            "topic": "Topic",
            "quote": "Gurbani Quote",
            "katha": ""  # No header for regular katha
        }
        return headers.get(section_type, "")
    
    def _format_timestamp(self, seconds: float) -> str:
        """Format timestamp as MM:SS."""
        minutes = int(seconds // 60)
        secs = int(seconds % 60)
        return f"{minutes:02d}:{secs:02d}"
    
    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters."""
        return (text
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;")
                .replace("'", "&#39;"))
    
    def _get_css(self) -> str:
        """Get embedded CSS styles."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
            max-width: 900px;
            margin: 0 auto;
        }
        
        .document-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .document-header h1 {
            font-size: 2.5em;
            margin-bottom: 15px;
        }
        
        .metadata {
            font-size: 0.9em;
            opacity: 0.9;
        }
        
        .metadata p {
            margin: 5px 0;
        }
        
        .document-content {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        
        .section {
            margin-bottom: 40px;
            padding-bottom: 30px;
            border-bottom: 1px solid #e0e0e0;
        }
        
        .section:last-child {
            border-bottom: none;
        }
        
        .section-header {
            color: #667eea;
            font-size: 1.8em;
            margin-bottom: 20px;
            border-left: 4px solid #667eea;
            padding-left: 15px;
        }
        
        .section-text {
            font-size: 1.1em;
            line-height: 1.8;
            color: #444;
        }
        
        .quote-block {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin: 20px 0;
            box-shadow: 0 4px 6px rgba(0,0,0,0.2);
        }
        
        .quote-gurmukhi {
            font-size: 2em;
            text-align: center;
            font-weight: bold;
            margin-bottom: 15px;
            line-height: 1.5;
        }
        
        .quote-roman {
            font-size: 1.2em;
            text-align: center;
            font-style: italic;
            margin-bottom: 10px;
            opacity: 0.95;
        }
        
        .quote-english {
            font-size: 1em;
            text-align: center;
            margin-bottom: 15px;
            opacity: 0.9;
            padding: 10px;
            background: rgba(255,255,255,0.1);
            border-radius: 5px;
        }
        
        .quote-metadata {
            font-size: 0.9em;
            text-align: center;
            margin-top: 15px;
            padding-top: 15px;
            border-top: 1px solid rgba(255,255,255,0.3);
            opacity: 0.85;
        }
        
        .quote-context {
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid rgba(255,255,255,0.3);
        }
        
        .quote-context ul {
            list-style: none;
            padding-left: 0;
        }
        
        .quote-context li {
            padding: 5px 0;
            opacity: 0.9;
        }
        
        .timestamp {
            font-size: 0.85em;
            color: #666;
            margin-top: 10px;
            font-style: italic;
        }
        
        .document-footer {
            text-align: center;
            margin-top: 40px;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }
        
        @media print {
            body {
                background: white;
                padding: 0;
            }
            
            .document-header {
                background: #667eea;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            
            .quote-block {
                background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
        """
